[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.update-version]
script = [
    "cargo set-version --bump patch",
    "cargo update-lockfile",
    "git add Cargo.toml Cargo.lock",
    "git commit -m 'Bump version to v${CARGO_MAKE_CRATE_VERSION}'",
    "git push",
    "git tag v${CARGO_MAKE_CRATE_VERSION}",
    "git push --tags"
]